---
- hosts: all-ubuntu
  become: yes
  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache is started
      service:
        name: apache2
        state: started
        enabled: true
